name: Trigger auto deployment for pgp-excel-agent

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'ExcelAgent/**'
    - '.github/workflows/pgp-excel-agent-AutoDeployTrigger-b72ad534-1023-4c15-935b-e3358bf1503a.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.PGPEXCELAGENT_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.PGPEXCELAGENT_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.PGPEXCELAGENT_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/ExcelAgent
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: pgpglassregistry.azurecr.io
          registryUsername: ${{ secrets.PGPEXCELAGENT_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.PGPEXCELAGENT_REGISTRY_PASSWORD }}
          containerAppName: pgp-excel-agent
          resourceGroup: pgp-glass-rg
          imageToBuild: pgpglassregistry.azurecr.io/pgp-excel-agent:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


